from .bfs1 import BFS1
from .bfs2 import BFS2
from .dfs import DFS
from .gs import Greedy_Search 
from .ids import IDS
from .usc import UCS
from .a_star import A_Star
from .ida import IDA
from .simple_hill_climbing import SHC
from .simple_hill_climbing_highest import SHC_Highest